-- QuickBite — Food Delivery Order & Restaurant Management System


SET client_min_messages = warning;   -- hide "does not exist, skipping"

DROP TABLE IF EXISTS payment, order_item, food_order, menu_item,
                     delivery_agent, customer, restaurant CASCADE;

-- ---------------------------------------------------------------------
-- RESTAURANT
-- Cuisine and address live here ONCE (previously repeated on every
-- menu-item row). Menu items reference it via restaurant_id  -> 2NF fix.
-- ---------------------------------------------------------------------
CREATE TABLE restaurant (
    restaurant_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cuisine VARCHAR(40) NOT NULL,
    location VARCHAR(60) NOT NULL,           -- area / locality
    address VARCHAR(200) NOT NULL,           -- street address
    phone VARCHAR(15) NOT NULL UNIQUE,
    rating NUMERIC(2,1) CHECK (rating BETWEEN 0 AND 5),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_restaurant_name_location UNIQUE (name, location)
);

-- ---------------------------------------------------------------------
-- MENU_ITEM   (Restaurant 1 : M MenuItem)
-- ---------------------------------------------------------------------
CREATE TABLE menu_item (
    menu_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INTEGER NOT NULL
                REFERENCES restaurant(restaurant_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    name VARCHAR(100)  NOT NULL,
    category VARCHAR(30)   NOT NULL
            CHECK (category IN ('Starter','Main Course','Bread','Rice',
                                'Dessert','Beverage','Snack','Combo')),
    price NUMERIC(8,2)  NOT NULL CHECK (price > 0),
    is_veg BOOLEAN NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_menu_item_per_restaurant UNIQUE (restaurant_id, name)
);

-- ---------------------------------------------------------------------
-- CUSTOMER
-- ---------------------------------------------------------------------
CREATE TABLE customer (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100)  NOT NULL,
    email VARCHAR(120)  NOT NULL UNIQUE,
    phone VARCHAR(15)   NOT NULL UNIQUE,
    address VARCHAR(200)  NOT NULL,
    location VARCHAR(60)   NOT NULL,
    joined_on DATE  NOT NULL DEFAULT CURRENT_DATE
);

-- ---------------------------------------------------------------------
-- DELIVERY_AGENT
-- ---------------------------------------------------------------------
CREATE TABLE delivery_agent (
    delivery_agent_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100)  NOT NULL,
    phone VARCHAR(15)   NOT NULL UNIQUE,
    vehicle_type VARCHAR(20)   NOT NULL
                CHECK (vehicle_type IN ('Bicycle','Scooter','Motorbike','EV Scooter')),
    vehicle_no VARCHAR(15) UNIQUE,              -- NULL for bicycles
    home_zone VARCHAR(60) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------
-- FOOD_ORDER
--   Customer       1 : M FoodOrder
--   Restaurant     1 : M FoodOrder
--   DeliveryAgent  1 : M FoodOrder
-- All three FKs are NOT NULL -> every order ties to a valid restaurant,
-- customer and delivery agent (referential integrity outcome).
-- ---------------------------------------------------------------------
CREATE TABLE food_order (
    order_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       INTEGER      NOT NULL
                      REFERENCES customer(customer_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
    restaurant_id     INTEGER      NOT NULL
                      REFERENCES restaurant(restaurant_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
    delivery_agent_id INTEGER      NOT NULL
                      REFERENCES delivery_agent(delivery_agent_id)
                      ON UPDATE CASCADE ON DELETE RESTRICT,
    order_time        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivery_address  VARCHAR(200) NOT NULL,           -- snapshot at order time
    status            VARCHAR(20)  NOT NULL DEFAULT 'Placed'
                      CHECK (status IN ('Placed','Preparing','Out for Delivery',
                                        'Delivered','Cancelled')),
    delivered_time    TIMESTAMP,
    CONSTRAINT chk_delivered_after_order
        CHECK (delivered_time IS NULL OR delivered_time > order_time),
    CONSTRAINT chk_delivered_has_time
        CHECK (status <> 'Delivered' OR delivered_time IS NOT NULL)
);

-- ---------------------------------------------------------------------
-- ORDER_ITEM  (order-lines; resolves FoodOrder M : N MenuItem)
-- unit_price is the price charged at order time (menu prices change
-- later), so it is a fact about the order line, not a redundant copy.
-- ---------------------------------------------------------------------
CREATE TABLE order_item (
    order_id INTEGER NOT NULL
            REFERENCES food_order(order_id)
            ON UPDATE CASCADE ON DELETE CASCADE,
    menu_item_id INTEGER NOT NULL
                REFERENCES menu_item(menu_item_id)
                ON UPDATE CASCADE ON DELETE RESTRICT,
    quantity SMALLINT NOT NULL CHECK (quantity BETWEEN 1 AND 50),
    unit_price NUMERIC(8,2)  NOT NULL CHECK (unit_price > 0),
    PRIMARY KEY (order_id, menu_item_id)
);

-- ---------------------------------------------------------------------
-- PAYMENT   (FoodOrder 1 : 1 Payment — UNIQUE FK enforces the "1")
-- ---------------------------------------------------------------------
CREATE TABLE payment (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL UNIQUE
            REFERENCES food_order(order_id)
            ON UPDATE CASCADE ON DELETE CASCADE,
    method          VARCHAR(10)  NOT NULL
                    CHECK (method IN ('UPI','Card','Cash','Wallet')),
    status          VARCHAR(10)  NOT NULL
                    CHECK (status IN ('Pending','Paid','Refunded','Failed')),
    transaction_ref VARCHAR(40)  UNIQUE,               -- NULL for cash
    paid_at         TIMESTAMP
);

-- ---------------------------------------------------------------------
-- Business rule a plain FK cannot express: every line of an order must
-- be a dish from THAT order's restaurant. Enforced with a trigger, so
-- order_item stays in 2NF (no copied restaurant_id).
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_order_item_same_restaurant()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT restaurant_id FROM menu_item  WHERE menu_item_id = NEW.menu_item_id)
       IS DISTINCT FROM
       (SELECT restaurant_id FROM food_order WHERE order_id     = NEW.order_id) THEN
        RAISE EXCEPTION
            'Menu item % does not belong to the restaurant of order %',
            NEW.menu_item_id, NEW.order_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER order_item_same_restaurant
BEFORE INSERT OR UPDATE ON order_item
FOR EACH ROW EXECUTE FUNCTION trg_order_item_same_restaurant();

-- ---------------------------------------------------------------------
-- Derived data is computed, not stored (avoids update anomalies):
-- order total = SUM(quantity * unit_price) over its lines.
-- ---------------------------------------------------------------------
CREATE VIEW v_order_total AS
SELECT fo.order_id,
       fo.restaurant_id,
       fo.customer_id,
       fo.status,
       fo.order_time,
       SUM(oi.quantity * oi.unit_price)::NUMERIC(10,2) AS order_total
FROM   food_order fo
JOIN   order_item oi ON oi.order_id = fo.order_id
GROUP  BY fo.order_id;
